# Generated by Django 5.2.4 on 2025-08-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(verbose_name=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
