# Generated by Django 5.2.6 on 2025-09-22 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thema', models.CharField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubThema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subthema', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('thema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.thema')),
            ],
        ),
    ]
